### ISSUE TITLE
Team, Player and Season Constraint.

### ISSUE THREAD

**Issue by endrawes0** [cyanfish/heltour#100]
The website lets admins add players to teams for seasons that the player has not been added to.

I feel like there should be a constraint that teams associated with a particular season should not be allowed to contain players who are not in that season.

Is that something that can be easily done on your side?

**Comment by cyanfish** [comment]
Fixed with https://github.com/cyanfish/heltour/commit/89515c13733c6f85900f5914434f003147ca3caf
