### ISSUE TITLE
Yellow cards and unavailable should be more distinguishable

### ISSUE THREAD

**Issue by lakinwecker** [cyanfish/heltour#104]
Maybe use a strike-through for unavailable and a yellow-card icon for yellow cards.

**Comment by lakinwecker** [comment]
https://icons8.com/web-app/30862/soccer-yellow-card

**Comment by cyanfish** [comment]
I changed the unavailable color to orange - thoughts on that?

**Comment by lakinwecker** [comment]
Since filing this issue, I realized that yellow cards and unavailable don't show up on the same pages. So I'm less concerned about it. Either way, let's ask the other mods what they think as I think a visual distinction is useful.

The orange is OK, but I still think that an icon or something maybe even '(unavilable)' or strikethrough would be better. But then again I'm partially colour blind, so the difference between orange and yellow isn't as visually distinctive as something else might be for me.

**Comment by cyanfish** [comment]
That's a good point, we should probably try and add an additional visual indicator besides color, ideally for all the different highlights.

**Comment by tnan123** [comment]
now they show up on the same page (rosters). Issue still open to further distinguish unavailable from YC?? (strikethrough etc) I say close it, no?

**Comment by cyanfish** [comment]
Thoughts on these icons?
https://staging.lichess4545.com/team4545/season/5/rosters/

**Comment by cyanfish** [comment]
Icons have been added in addition to the color highlights.
