### ISSUE TITLE
TV Page didn't work on Firefox 43 in windows xp

### ISSUE THREAD

**Issue by lakinwecker** [cyanfish/heltour#106]
I'm not sure if we'll be able to track this down, but alex_1987 mentioned that the TV page isn't working for them on windows xp on firefox 43. Here is the browser information:

http://whatsmybrowser.org/b/I4EB6LJ
![screen](https://cloud.githubusercontent.com/assets/248376/18970582/025ce814-864f-11e6-8b83-f687578422f0.jpg)

Above is the screenshot. And it might have to do with the the add-on noscript. They confirmed that chrome works fine.

**Comment by cyanfish** [comment]
I doubt there's anything we can do about this, so closing this issue.

**Comment by lakinwecker** [comment]
I have access to a browserstack account through work, I could have a quick look to see if I can reproduce it, if you think it's worth while?

**Comment by lakinwecker** [comment]
![firefox-43-windows-xp](https://cloud.githubusercontent.com/assets/248376/19871971/15030092-9f7d-11e6-80ac-e483aa7cdf2b.png)

This is the error that the developer tools show in firefox 43 in windows xp

**Comment by cyanfish** [comment]
Ah, interesting. The "let" statement is the issue. https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/let#Browser_compatibility

Can you test it again on staging? I pushed a possible fix.

**Comment by lakinwecker** [comment]
Yeah, that works.
