### ISSUE TITLE
Add flip option to boards on TV

### ISSUE THREAD

**Issue by endrawes0** [cyanfish/heltour#107]
I would love to flip the board on the TV page - what do you think?

**Comment by lakinwecker** [comment]
I am in favour. I was thinking about adding a few controls to the boards. They would be especially useful on mobile.

**Comment by cyanfish** [comment]
Implemented. Hover over a board and you'll see a menu button.

**Comment by endrawes0** [comment]
just saw this. fantastic. thanks @cyanfish
