### ISSUE TITLE
Old Lonewolf tournaments

### ISSUE THREAD

**Issue by tnan123** [cyanfish/heltour#109]
Any plans to upload older seasons prior to Lonewolf#4 or are the sheets lost forever?

**Comment by cyanfish** [comment]
We have access to the sheets from Seasons 2 and 3, but haven't gotten around to trying to import/fix them yet.

**Comment by lakinwecker** [comment]
The older lonewolf didn't use formulas for any of the data fields, it was all copy/paste. So I'm 99% certain that they are as correct as is necessary to import them.  The only concern will be any formatting/layout differences.

**Comment by cyanfish** [comment]
I know Lonewolf 3 has a bunch of issues. I tried importing it the same way as #4 but the standings were completely wrong. For example, my round 1 game isn't listed on the round 1 sheet. My plan (that I never got around to implementing) was to get the results from the standings sheet and only use the pairing sheets to get the gamelinks.

**Comment by lakinwecker** [comment]
Interesting.  Have you run into other problems? that one looks like a user input error that happened at some point after the original pairing was finished.  We should be able to go back and copy/paste each worksheet from the last day of the round.

I guess using the wallchart/standings sheet works too.

**Comment by cyanfish** [comment]
Lonewolf 3 is now up on the site: https://www.lichess4545.com/lonewolf/season/3/summary/

**Comment by cyanfish** [comment]
Lonewolf 2 is also up now: https://www.lichess4545.com/lonewolf/season/2/summary/
