### ISSUE TITLE
Comparison of individual performances

### ISSUE THREAD

**Issue by tnan123** [cyanfish/heltour#111]
Now that we can compute perf rating for individual players (https://github.com/cyanfish/heltour/issues/95), an enhancement would be to be able to compare individual players stats (perf rating and total score) on one page.

Perhaps by board or just overall. Not sure how it would be organized.

**Comment by cyanfish** [comment]
This can now be viewed here:
https://www.lichess4545.com/team4545/season/5/board/1/scores/

There is currently no direct link on the site. The expectation is that we will link to it manually from end-of-season documents.
