### ISSUE TITLE
ratings not updated every 30 minutes

### ISSUE THREAD

**Issue by lakinwecker** [cyanfish/heltour#113]
While working on the chesster rating issue (which I believe I've solved) I noticed that the ratings are not being updated every 30 minutes.

I can provide a specific example, but I'm not sure if it'll still be out of date by the time you look into it

**Comment by cyanfish** [comment]
I think I've finally tracked this down. The issue was that a random network issue would cause an unexpected exception and crash the API worker thread. I've added some additional error handling to fix it. https://github.com/cyanfish/heltour/commit/36eaf9bec8e2a3e91af4c207fd465b81ccf6c692
