### ISSUE TITLE
Staging environment is indexed by Google

### ISSUE THREAD

**Issue by kuc** [cyanfish/heltour#115]
This is no good 👎 
The easiest way to fix this is adding HTTP headers to all responses from staging server:
```
X-Robots-Tag: noindex, nofollow, noarchive
```

https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag?hl=en

**Comment by lakinwecker** [comment]
Agreed. If cyanfish doesn't get to it before I do, I'll do that tonight.

**Comment by kuc** [comment]
@lakinwecker I am just finishing pull request 😉

**Comment by lakinwecker** [comment]
GReat!
