### ISSUE TITLE
Performance rating calculations and forfeited games

### ISSUE THREAD

**Issue by lakinwecker** [cyanfish/heltour#118]
According to FIDE, we shouldn't be including forfeits in the rating performance calculations. 

https://www.fide.com/component/handbook/?id=174&view=article

"1.42d - Games which are decided by forfeit, adjudication or any means other than over the board play. Other games once started, which are forfeited for whatever reason, shall however be included. In the instance of a last round game where the opponent forfeits, the norm shall still count if the player must play in order to have the required number of games, but can afford to lose."

It's unclear to me if results that were turned into forfeits due to engine assistance should be counted or not. I think not.  If only because "1.42b - Games against computers."

Thoughts?

**Comment by cyanfish** [comment]
I agree with that, althought this statement is not easy to account for: "Other games once started, which are forfeited for whatever reason, shall however be included."

Right now, all games with forfeit results are not counted, which I think is a reasonable approach.
https://github.com/cyanfish/heltour/blob/master/heltour/tournament/views.py#L839
https://github.com/cyanfish/heltour/blob/master/heltour/tournament/models.py#L971

**Comment by lakinwecker** [comment]
https://www.lichess4545.com/team4545/season/5/player/darksquaregames/ <- 7.5 / 8 when there is clearly a forfeit loss in there.  Something isn't working

**Comment by lakinwecker** [comment]
I agree. It's hard to account for "Other games once started, which are forfeited for whatever reason, shall however be included." I'm not convinced there is much we can do for that. Unfortunately.

**Comment by lakinwecker** [comment]
I see. The Score does take into account forfeit wins, which makes sense. The performance rating does not. I guess I was just confused by that on this page: https://www.lichess4545.com/team4545/season/5/board/1/scores/

But I see how it works now. Thanks. We can open a different issue to track making that page more clear.
