### ISSUE TITLE
Don't send alternate notifications to players that are both unavailable and have a red card

### ISSUE THREAD

**Issue by cyanfish** [cyanfish/heltour#167]

**Comment by lakinwecker** [comment]
Also don't send the initial pairing DM to this person. If someone is marked as unavailable, then the initial DM on the release of pairings should only be to the player that is not available and explains that they don't have an opponent yet. 

Or does it already work that way?

**Comment by cyanfish** [comment]
Actually it doesn't send any messages to either player right now, if they're marked unavailable before the round start.
The unavailable player (and captain) is notified when the search first starts, then if the round starts before the spot is filled, both captains are notified.

**Comment by cyanfish** [comment]
So we could fiddle with it a bit, but we might not need to change anything.

**Comment by lakinwecker** [comment]
Ok yeah, that sounds like we don't need to do anything.
