### ISSUE TITLE
Website api worker hammers /api/socket when lichess is deployed.

### ISSUE THREAD

**Issue by lakinwecker** [cyanfish/heltour#179]
This should backoff slowly or quickly or just delay a few seconds.

**Comment by lakinwecker** [comment]
https://github.com/cyanfish/heltour/blob/master/heltour/api_worker/worker.py#L31

I suspect that should be a < rather than a >

**Comment by cyanfish** [comment]
Fixed in https://github.com/cyanfish/heltour/commit/63c4acd35c60d87e8e34fd7118e4b8c00624cb78
