### ISSUE TITLE
Alternates added late in a round aren't contacted in time

### ISSUE THREAD

**Issue by lakinwecker** [cyanfish/heltour#248]
An alternate was added to the board 3 list around midnight in UTC on August 1st. All previous alternates had been contacted and there was a board 3 vacancy.  18 hours later at 18:00 on August 1st, this alternate still hasn't been contacted. 

It appears that this alternate search is set to "all alternates contacted". Perhaps this should be unset when we add a new alternate.

**Comment by cyanfish** [comment]
Fixed in https://github.com/cyanfish/heltour/commit/e76e3146d3a71f90b42c0911a210affb368cab46
