### ISSUE TITLE
Allow importing of teams for the rosters page in team league

### ISSUE THREAD

**Issue by michael1241** [cyanfish/heltour#278]
Combined with the output from https://github.com/michael1241/lichess4545-teams allow for an automated import of teams from the team generation program directly into the admin - edit rosters page. (Copy pasting the output from the team generator into a form/field on the site for example).

**Comment by colwem** [comment]
Can you specify what form you're currently entering stuff into so I can figure out what it's doing then code that up directly into an api request.

**Comment by michael1241** [comment]
It's a bit weird to track down but the URL on the live site is https://www.lichess4545.com/admin/tournament/season/113/manage_players/ for this season. I've forgotten where it is exactly.. you can get there from the dashboard page though as an admin https://www.lichess4545.com/team4545/season/15/dashboard/

**Comment by cyanfish** [comment]
The code that processes team changes is here:
https://github.com/cyanfish/heltour/blob/4755add9989306bf3e871e5caaa1cd8516cf9b6c/heltour/tournament/admin.py#L825

**Comment by cyanfish** [comment]
That method is complicated by the effort to make modular changes with descriptive reversion comments. Full team import can be more simplistic.

**Comment by lakinwecker** [comment]
This is no longer relevant.
