### ISSUE TITLE
not_an_alternate error when assigning a player to play down a board using chesster

### ISSUE THREAD

**Issue by aebe** [cyanfish/heltour#302]
The captains guidelines for the 4545 league have the following instructions for assigning a player to play up or down a board:

> If no alternate can be found, but a player can play up or down a board from your team (in line with the rules), you can assign them to play up using the command "assign \<player\> to board \<b\> during round \<r\> on \<team name\>" in #captains - additionally captains must inform the opposing captain and opponent player of the new assignment.

When attempting to use this command to assign a player to play down a board, however, we get the not_an_alternate error:

> david252525 [10:21 AM]
> @ chesster assign @david252525 to board 4 during round 7 on More Zero Than Alpha

> chesster APP [10:23 AM]
> I failed to update alternate assignment: Error: not_an_alternate
> Please contact a moderator.

This error comes from heltour, more specifically api.py around line 315 (in the current master branch). I'm not familiar with the code base, but at first glance it looks like maybe it's checking if the player is playing up a board, but not playing down a board.

**Expected behavior**: captains should be able to assign their players to play down a board, as specified in the captains guidelines. Currently this seems to require moderator intervention.

**Comment by cyanfish** [comment]
Discussed with the mods and they would prefer to keep it this way. The captains guidelines should be updated.
