### ISSUE TITLE
update_pairing API endpoint

### ISSUE THREAD

**Issue by lakinwecker** [cyanfish/heltour#63]
Does this endpoint accept reversed white/black usernames? If it does not, can it?  And if it determines that white/black are reversed can it include a 'reversed': true in the response?

**Comment by cyanfish** [comment]
It doesn't, but my thought was that you could first call find_pairing (which does), and then call update_pairing based on the result of that. I can make this change if you'd prefer though.

**Comment by lakinwecker** [comment]
Sure, let me have a look at using that.

**Comment by cyanfish** [comment]
Implemented as discussed.
