### ISSUE TITLE
API: League moderators

### ISSUE THREAD

**Issue by cyanfish** [cyanfish/heltour#67]
Add an API endpoint to get moderators by league. Also replace the is_mod flag with a simple LeagueModerator model.

**Comment by endrawes0** [comment]
instead of creating an api endpoint for this, we could create a new document type instead and then utilize the league_document api endpoint.

**Comment by lakinwecker** [comment]
Then we'd have to scrape the HTML to be able to properly list the mods, right?

**Comment by endrawes0** [comment]
Oh, is that how the api returns it? I don't want that. What was the intended use of that api if it returns html?

**Comment by lakinwecker** [comment]
The league document probably returns urls to the league documents.  But this request is about being able to respond with:

The lonewolf moderators are: @endrawes0, @jptriton, @cyanfish 

So this API need to return a list of usernames. IMO.

**Comment by endrawes0** [comment]
The wiki looked like it returns content, not the URL. I haven't looked at the code

**Comment by endrawes0** [comment]
But of course, an api returning the list of users is most appropriate.

**Comment by cyanfish** [comment]
The league_document API has a strip_html parameter. So for example we could get it to return "The lonewolf moderators are: @endrawes0, @jptriton, @cyanfish" or simply "@endrawes0, @jptriton, @cyanfish" if we wanted to

The question is whether the website having structured information about who the moderators are is useful. I imagine it might be at some point (though I can't think of anything right now).

**Comment by lakinwecker** [comment]
Currently chesster has a setting that determines who are moderators, we use this information to allow some people to update any result/gamelink/schedule in the appropriate channels.

I don't want to have to do string parsing to get that information to continue that practice. I still think having an explicit "who are the moderators" API call will benefit chesster's coding.

**Comment by cyanfish** [comment]
Implemented. [Wiki](https://github.com/cyanfish/heltour/wiki/API-Endpoints) updated as usual.
