### ISSUE TITLE
API: Private url authentication

### ISSUE THREAD

**Issue by cyanfish** [cyanfish/heltour#68]
Create an API endpoint that takes a username and returns a url authenticated for that username

**Comment by endrawes0** [comment]
We may have other uses for this. I suggest making it generic.

You should return a private token that can be used for more than just voting.

**Comment by endrawes0** [comment]
But obviously for voting.

**Comment by lakinwecker** [comment]
We can also include commands for removing the token: `@chesster login`  `@chesster logout`  etc

**Comment by cyanfish** [comment]
Implemented a get_private_url endpoint ([wiki](https://github.com/cyanfish/heltour/wiki/API-Endpoints)). 

The way I have it implemented right now is you specify the page (e.g. "vote"), and it returns a URL with a token that has a fixed expiry time (1 hour for now). The token itself is not tied to a particular page, but in practice you would call the API to create a new token/url to visit another page.

**Comment by endrawes0** [comment]
Cool. Your productivity makes me feel worthless.
