### ISSUE TITLE
Every place a team name appears should link to 'team' page

### ISSUE THREAD

**Issue by lakinwecker** [cyanfish/heltour#73]
Same with the player profile, the teams should list the seasons they have participated in and the trophies won along with team members and alternates.

**Comment by cyanfish** [comment]
Mostly implemented. I'm not sure if I want to put a link between seasons since there's no guarantee that a team with the same name has the same players. Trophies will be implemented alongside https://github.com/cyanfish/heltour/issues/71.

**Comment by lakinwecker** [comment]
I agree, I'm not sure the link between the seasons is worth it. For now, I just want to always be able to get to a team page when I see their name.
