### ISSUE TITLE
Create a League History page

### ISSUE THREAD

**Issue by endrawes0** [cyanfish/heltour#74]
Make it possible for admins to add events

I think we just need time, summary, and detail for each event.

I am thinking stuff like:
Oct 2015 - It started small... 
- The first season of the Lichess 4545 league was small in nearly every way. The league only had 10 teams Teams only contained 4 players. ... I am not a good writer, but you get the idea.

Season 1 - Creation of the Lone Wolf League
- Details... blah blah and blah. Plus dont for get about the blah blah blah.

**Comment by cyanfish** [comment]
How about an unstructured document? e.g. https://www.lichess4545.com/team4545/document/league-history/

We would just need to add a link to it somewhere - maybe the homepage or FAQ.

**Comment by endrawes0** [comment]
this is just fine. thanks!

I didnt realize that was an option.

**Comment by tnan123** [comment]
https://www.lichess4545.com/team4545/document/league-history/ Done!
