### ISSUE TITLE
TV Page

### ISSUE THREAD

**Issue by lakinwecker** [cyanfish/heltour#8]
Make a TV page that shows all active games with game links. For now it can link to each game, but once https://github.com/ornicar/lila/issues/2096 is done, it can embed them with an iframe.

It should use a websocket or polling request to remove games after they are done (say 5 minutes after wards) and add new games as soon as they start.  

The ordering should probably be by time started, so that new games are always added to the end of it, rather in the middle, but perhaps there are other ways of figuring this out.

**Comment by cyanfish** [comment]
The league homepage has a static list of ongoing games based only on scheduled time and the game link. I'm going to leave anything more elaborate until later, since I want to look at that lichess issue and see if I can submit a PR for it.

**Comment by cyanfish** [comment]
https://github.com/cyanfish/heltour/issues/81
https://github.com/cyanfish/heltour/issues/82
