### ISSUE TITLE
Individual performances on Stats page

### ISSUE THREAD

**Issue by tnan123** [cyanfish/heltour#95]
At least 4 players from season 4 in their feedback comments mentioned this:
"I would love to be able to see individual player scores from the team league"
"It's pretty sweet, I'd like to see a page for everyones individual score across all 8 rounds, so that we can easily identify players that are doing really well"
"Stats for specific players rather than just team performance"
"compute perf ratings for players"

**Comment by cyanfish** [comment]
An individual's performance rating can now be seen on the player profile page (if they have 5+ games played in the season).

**Comment by tnan123** [comment]
yay!! great work cyanfish :+1:
